import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import axios from "axios";
import "bootstrap/dist/css/bootstrap.min.css";
window.axios = axios;
import { registerGlobalComponent } from "./utils/import";
const app = createApp(App);
registerGlobalComponent(app);
app.use(router);
app.mount("#app");
